Development checkpoint.

diff --git a/bin/void_linux b/bin/void_linux
--- a/bin/void_linux
+++ b/bin/void_linux
@@ -196,6 +196,23 @@ case "$@" in
       chmod go-rwX "$HOME/bin/secrets"
     fi
 
+    if ! which battery.monitor >/dev/null ; then
+      echo "!!! not found in path: battery.monitor" >&2
+      exit 1
+    fi
+
+    if battery.monitor has battery ; then
+      if test "$(battery.monitor status)" = "charging" ; then
+        :
+      else
+        if test "$(battery.monitor current)" -lt 40 ; then
+          echo "!!! Plug laptop has low battery and discharging." >&2
+          exit 1
+        fi
+      fi
+    fi
+
+
     set -x
     sudo xbps-install -Su || {
       sudo xbps-install -u xbps;
